### ISSUE TITLE
very cool!

### ISSUE THREAD

**Issue by swuecho** [ocaml-ci/ocaml-ci#40]
come here from https://discuss.ocaml.org/t/ann-capnp-rpc-0-4-0/4524. The doc is one of the best among ocaml lib. 

Amazing that whole project is using ocaml. Would like to know how this happen. Especially, how to call capnp-rpc service in the frontend. Can I call the backend service using Javascript from web browser?

**Comment by talex5** [comment]
Here's an example of the web frontend calling the backend:

https://github.com/ocaml-ci/ocaml-ci/blob/f9610e2e95b050e958b2428d0aaab021fa2487f8/web-ui/github.ml#L173-L176

I don't think web browsers will let you open a plain TCP socket from Javascript, so you'd need some kind of web-sockets proxy. Apart from that it should work. I'm planning to split the networking stuff out of capnp-rpc-lwt, which would make the core library smaller and easier to compile to Javascript.
